extends Node

signal signal_level_won
signal signal_level_advance
signal signal_level_fail
signal signal_level_reset

signal signal_change_level_run_state
signal signal_level_run_state_changed


signal signal_pickitem_pickup
signal signal_pickitem_drop
signal signal_pickitem_drop_update_inventory
signal signal_pickitem_cancel

signal signal_gird_indicaotr_show
signal signal_gird_indicaotr_dismiss


signal signal_step_update
signal signal_cell_arraived

signal signal_hp_update
signal signal_str_update
signal signal_energy_update

signal signal_inventory_capacity_increase
